### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by haofoss** [haofoss/slight-fimulator#3]
On launch:
```
user@hostname:~/Desktop$ python slight-fimulator-1.0.1/
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/Desktop/slight-fimulator-1.0.1/__main__.py", line 9, in <module>
    import __init__
  File "slight-fimulator-1.0.1/__init__.py", line 269, in <module>
    logo = pygame.image.load("%s/Images/logo.png" % PATH)
pygame.error: Couldn't open /home/user/Desktop/slight-fimulator-1.0.1/Images/Images/logo.png
```

To fix, remove "Images" when setting the PATH variable.

**Comment by MasterofNumbers17** [comment]
Go ahead! (I thought I did that!)

**Comment by MasterofNumbers17** [comment]
Fix complete.
